# Site settings
name: Blog  of JamesPxy
email: 1516462744@qq.com
author: JamesPxy
#url: http://jamespxy.github.io
url: http://pengxiaoyong.cn
resume_site: http://jamespxy.github.io/
github: https://github.com/JamesPxy/
baseurl: "/MyBlog"
description: Action speaks louder than  words , Just do  it !
meta_description: JamesPxy的个人博客，每日积累，厚积薄发！
motto: 每日积累，厚积薄发！
banner:  不忘初心，砥砺前行！水滴石穿，贵在坚持！

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: JamesPxy
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : jamespxy
    # disqus :
    #     short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
theme: jekyll-theme-merlot
